name: Check Release
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["*"]

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - name: Check Release
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        uses: jupyter-server/jupyter_releaser/.github/actions/check-release@v2
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Upload Distributions
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        uses: actions/upload-artifact@v3
        with:
          name: jupyterlab_disable_copyoutputs-releaser-dist-${{ github.run_number }}
          path: .jupyter_releaser_checkout/dist
